import type { Metadata } from "next";
import { Footer, Layout, Navbar, ThemeSwitch } from "nextra-theme-blog";
import "nextra-theme-blog/style.css";
import { Banner, Head, Search } from "nextra/components";
import { getPageMap } from "nextra/page-map";

// import "@/styles/globals.css";

import { geistMono, geistSans } from "./fonts";

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const banner = <Banner storageKey="4.0-release">Site is under construction</Banner>;

  return (
    <html lang="en" suppressHydrationWarning>
      <Head backgroundColor={{ dark: "#0f172a", light: "#fefce8" }} />
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Layout banner={banner}>
          <Navbar pageMap={await getPageMap()}>
            <Search />
            <ThemeSwitch />
          </Navbar>

          {children}

          <Footer>
            <abbr
              title="This site and all its content are licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
              style={{ cursor: "help" }}
            >
              CC BY-NC 4.0
            </abbr>{" "}
            {new Date().getFullYear()} © Egor Makarenko.
            <a href="/feed.xml" style={{ float: "right" }}>
              RSS
            </a>
          </Footer>
        </Layout>
      </body>
    </html>
  );
}
