import type { Metadata } from "next";

import { Link } from "@/i18n/navigation";

import { posts } from "./posts";

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

function Post({ ...props }) {
  return (
    <div key={props.slug} className="daisy-card w-96 bg-base-100 shadow-sm">
      <div className="daisy-card-body">
        <Link href={`/blog/${props.slug}`} className="daisy-card-title">
          {props.title}
        </Link>
        <p>{props.description}</p>
      </div>
    </div>
  );
}

export default function Page() {
  return (
    <div className="flex flex-wrap gap-4 p-4">
      {posts.map(({ Content: _, ...props }) => (
        <Post key={props.slug} {...props} />
      ))}
    </div>
  );
}
