import type { Metadata } from "next";

import { getPosts } from "./posts";

export const metadata: Metadata = {
  title: "Blog",
  description: "Generated by create next app",
};

export default function Page() {
  const posts = getPosts();
  return (
    <div className="flex flex-wrap gap-4 p-4">
      {posts.map((post) => (
        <div key={post.slug} className="daisy-card w-96 bg-base-100 shadow-sm">
          <div className="daisy-card-body">
            <h2 className="daisy-card-title">{post.slug}</h2>
            <p>A card component has a figure, a body part, and inside body there are title and actions parts</p>
            <div className="daisy-card-actions justify-end">
              <button className="daisy-btn daisy-btn-primary">Open</button>
            </div>
          </div>
        </div>
      ))}
    </div>
  );
}
