import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default async function Page() {
  const { default: Content } = await import(`@/../content/home.mdx`);

  return (
    <main className="min-h-screen bg-base-200 py-8">
      <div className="container mx-auto px-4 md:px-6 max-w-7xl">
        <Content />
      </div>
    </main>
  );
}
